services:
  - type: web
    name: ai-coaching-conversation-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: microphone=(), camera=()
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_ENVIRONMENT
        value: production
      - key: REACT_APP_APP_NAME
        value: AI Coaching Conversation
      - key: REACT_APP_APP_VERSION
        value: 1.0.0
      - key: REACT_APP_ENABLE_VOICE_MODE
        value: true
      - key: REACT_APP_ENABLE_TEXT_MODE
        value: true
      - key: REACT_APP_ENABLE_DEMO_MODE
        value: false
      - key: REACT_APP_ENABLE_API_KEY_VALIDATION
        value: true
      - key: REACT_APP_MAX_MESSAGE_LENGTH
        value: 2000
      - key: REACT_APP_ENABLE_CACHING
        value: true
      - key: REACT_APP_CACHE_DURATION
        value: 300000
